###

GET http://localhost:6724/index.html
Content-Type: text/html;charset=UTF-8

###

GET http://localhost:6724
Content-Type: text/html;charset=UTF-8

###

GET http://localhost:6724
accept: application/lnwza007+json

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["hsZEOtaDsENYkP5H-JIWp"]
