###

GET http://localhost:6724/index.html
Content-Type: text/html;charset=UTF-8

###

GET http://localhost:6724
Content-Type: text/html;charset=UTF-8

###

GET http://localhost:6724
accept: application/nostr+json

###

WEBSOCKET ws://localhost:6724
Content-Type: application/json

["REQ","hsZEOtaDsENYkP5H-JIWp",{"kinds": [1],"limit": 2}, {"kinds": [4],"limit": 150}]
